# Generated by Django 4.0.10 on 2023-12-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('linkedin_profile', models.URLField(null=True)),
                ('industry', models.CharField(max_length=1000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_update_login', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='basic', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_update_login', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_update_login', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.package'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.userrole'),
        ),
    ]
