# Generated by Django 4.0.10 on 2023-12-12 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organization_package_userrole_packagestatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.package'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.userrole'),
        ),
    ]
