# Generated by Django 4.0.10 on 2024-01-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_package_name_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='facebook_profile',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_profile',
            field=models.URLField(null=True),
        ),
    ]
