# Generated by Django 4.0.10 on 2024-01-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_package_price_id_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_checkout_id',
            new_name='payment_intent_id',
        ),
    ]
